runtime: python311
entrypoint: GOOGLE_APPLICATION_CREDENTIALS=secrets/google-credentials.json NLTK_DATA=gaedata gunicorn -k gthread -b :$PORT main:app --timeout 120 --workers 1 --threads 1 
default_expiration: "300d 5h"

handlers:

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  http_headers:
    Vary: Accept-Encoding
  expiration: "0d 1h"

- url: /apple-touch-icon.png
  static_files: static/images/apple-touch-icon.png
  upload: static/images/apple-touch-icon.png

- url: /BingSiteAuth.xml
  static_files: static/BingSiteAuth.xml
  upload: static/BingSiteAuth.xml

- url: /static/*
  static_dir: static
  http_headers:
    Vary: Accept-Encoding

- url: .*
  script: main.app

instance_class: F1
automatic_scaling:
  max_idle_instances: 1
  target_cpu_utilization: .95
  target_throughput_utilization: .95
  min_pending_latency: 300ms
  max_pending_latency: 15000ms
  max_concurrent_requests: 80
  
# automatic_scaling:
#   min_idle_instances: 2
#   max_pending_latency: 4.5s

inbound_services:
- warmup


